name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      
jobs: 
  deploy_image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: install gcloud sdk
          uses: cobraz/setup-gke-gcloud-auth-plugin@v1
        - id: auth
          uses: google-github-actions/auth@v0.4.0
          with:
            credentials_json: ${{ secrets.JSONAUTH }}
            service_account: 'deployment@project-semester-6-387321.iam.gserviceaccount.com'

        - id: get-gke-credentials
          uses: google-github-actions/get-gke-credentials@v0.4.0
          with:
            location: us-central1
            cluster_name: pictacular

        - name: Apply deployment
          run: kubectl apply -f minikube/gateway.yaml
        - name: Restart deployment
          run: |
            kubectl rollout restart deploy indv-gateway --namespace=imani-indv
            kubectl rollout restart deploy description-cud --namespace=imani-indv
            kubectl rollout restart deploy description-r --namespace=imani-indv
            kubectl rollout restart deploy user-service --namespace=imani-indv
            kubectl rollout restart deploy description-mysql --namespace=imani-indv
            kubectl rollout restart deploy database-user --namespace=imani-indv
            kubectl rollout restart deploy rabbitmq --namespace=imani-indv




