name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      
jobs: 
  deploy_image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: install gcloud sdk
          run: |
            REPO_URL="https://packages.cloud.google.com/apt"
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
            sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg

            sudo apt-get update -y
            sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
        - name: Generate kube configuration
          run: |
            mkdir ~/.kube
            touch ~/.kube/config
            echo "${{ secrets.KUBE_CONF }}" >> ~/.kube/config

        - name: Apply deployment
          run: kubectl apply -f minikube/gateway.yml
        - name: Restart deployment
          run: |
            kubectl rollout restart deploy indv-gateway
            kubectl rollout restart deploy description-cud
            kubectl rollout restart deploy description-r
            kubectl rollout restart deploy user-service
            kubectl rollout restart deploy description-mysql
            kubectl rollout restart deploy database-user
            kubectl rollout restart deploy rabbitmq




